services:
  web:
    build: .
    command: [ "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ".:/code"
      - "/home/blogharu/kubernetes/blogharu/pv/baseball_of_korea:/pv"
    ports:
      - "443:443"
