# Generated by Django 4.2.3 on 2023-07-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created'], name='post_post_created_22b748_idx'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
